### ISSUE TITLE
make a Fly.io deploy

### ISSUE THREAD

**Issue by gedw99** [mearaj/bhagad-house-booking#6]
Fly.io has a postgresql already we can use.

It's also free for one project. 

Its does scaling out to many regions with the DB synced for you between the regions.
SO users get much faster experience because the fly.io proxy automatically directs the usr to the closest / fastest region.

https://fly.io/blog/globally-distributed-postgres/

https://fly.io/docs/getting-started/multi-region-databases/

We can adapt the makefile / and hence CI to autodeploy releases to FLY later.
We can also make it autodeploy PR's later.

**Comment by mearaj** [comment]
It's done.
Thanks a lot :)
